<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
	
	<a class="rename" href="<?php echo CHAMPION_ADMIN_URL; ?>/index.php?p=rename&d=<?php echo \htmlentities($view_model->param_get_f); ?>&e=<?php echo \htmlentities($view_model->param_get_ext); ?>">[<?php echo \htmlentities($GLOBALS['lang_rename_btn']); ?>]</a>
</div>

<div class="championcore">
	
	<br />
	
	<!-- preview -->
	<p>
		<b><?php echo \htmlentities($GLOBALS['lang_home_preview']); ?></b>:
		<a target="_blank" href="<?php echo CHAMPION_BASE_URL; ?>/content/<?php echo \htmlentities($view_model->param_get_f) . '.' . \htmlentities($view_model->param_get_ext); ?>"> <?php echo \htmlentities( $view_model->file_info['basename'] ); ?> </a>
	</p>
	<br />
	
	<!-- replace -->
	<a class="btn" href="<?php echo CHAMPION_ADMIN_URL; ?>/index.php?p=media_upload_handler&gallery=<?php echo \htmlentities($view_model->param_get_f); ?>&item=<?php echo \htmlentities($view_model->param_get_f); ?><?php echo \htmlentities($view_model->param_get_ext); ?>">
		<?php echo \htmlentities($GLOBALS['lang_media_replace']); ?>
	</a>
	<br />
	<br />
	
	<!-- move -->
	<form class="animated zoomIn" id="textfile" name="textfile" method="post" action="">
		<p>
			<label><?php echo \htmlentities($GLOBALS['lang_create_media_move']); ?></label>
			<select class="page-template-input" type="text" name="block_move">
				<option value=""></option>
				<?php foreach ($view_model->media_piles as $value) { ?>
						<option value="<?php echo \htmlentities($value->get_location()); ?>" <?php echo (($view_model->media_pile_directory == $value->get_location()) ? 'selected' : ''); ?>><?php echo \htmlentities($value->get_location()); ?></option>
				<?php } ?>
			</select>
		</p>
		
		<button class="btn save" type="submit" name="savetext"><?php echo \htmlentities($GLOBALS['lang_save']); ?></button>
		
		<input type="hidden" name="filename"  value="<?php echo \htmlentities($view_model->param_get_f) . '.' . \htmlentities($view_model->param_get_ext); ?>" />
		<input type="hidden" name="fname"     value="<?php echo \htmlentities($view_model->fname[0]); ?>" />
		<input type="hidden" name="textblock" value="foo" />
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
	</form>
	<br />
	<br />
	
	<p class="img-info"><b><?php echo \htmlentities($GLOBALS['lang_gal_filename']); ?></b> <?php echo \htmlentities( $view_model->file_info['basename'] ); ?> </p>
	<p class="img-info"><b><?php echo \htmlentities($GLOBALS['lang_gal_size']); ?></b>     <?php echo \htmlentities( $view_model->file_size ); ?> </p>
	<p class="img-info"><b><?php echo \htmlentities($GLOBALS['lang_gal_audio']); ?></b>&#60;audio src="<?php echo \htmlentities($view_model->param_get_f . '.' . $view_model->param_get_ext); ?>' controls &#62; &#60;/audio&#62;</p>
	<p class="img-info"><b><?php echo \htmlentities($GLOBALS['lang_gal_video']); ?></b>&#60;video src="<?php echo \htmlentities($view_model->param_get_f . '.' . $view_model->param_get_ext); ?>' controls &#62; &#60;/video&#62;</p>
	<p class="img-info"><b><?php echo \htmlentities($GLOBALS['lang_gal_link']); ?></b>&#60;a href="<?php echo \htmlentities($view_model->param_get_f . '.' . $view_model->param_get_ext); ?>"&#62;Link Text&#60;/a&#62;</p>
	
	<?php /*include (CHAMPION_ADMIN_DIR . '/inc/captions.php');*/ ?>
	
</div>
