
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
	
	<a class="rename" href="<?php echo CHAMPION_ADMIN_URL; ?>/index.php?p=rename&d=<?php echo \htmlentities($view_model->param_get_f); ?>&e=<?php echo \htmlentities($view_model->param_get_ext); ?>">[<?php echo \htmlentities($GLOBALS['lang_rename_btn']); ?>]</a>
</div>

<div class="championcore">
	
	<br />
	
	<?php if (!$view_model->flag_has_content) {
		echo $GLOBALS['lang_no_content'];
	} else { ?>
		
		<a class="embed_toggle" href="#"><?php echo $GLOBALS['lang_pages_options']; ?></a>
		
		<form class="" id="textfile" name="textfile" method="post" action=""> <!-- animated zoomIn -->
			
			<?php /* disable for now * / ?>
				<?php if ($view_model->force_textblock === false) { ?>
					<p>
						<br />
						<a href="<?php echo '//', $_SERVER['HTTP_HOST'], \str_replace('&force_textblock=1', '', $_SERVER['REQUEST_URI']); ?>&force_textblock=1">Edit this page in a standard textarea.</a>
					</p>
				<?php } else { ?>
					<p>
						<br />
						<a href="<?php echo '//', $_SERVER['HTTP_HOST'], \str_replace('&force_textblock=1', '', $_SERVER['REQUEST_URI']); ?>">Edit this page normally.</a>
					</p>
				<?php } ?>
			<?php */ ?>
			
			<div class="hide">
				
				<label><?php echo $GLOBALS['lang_blog_description']; ?></label>
				<input class="blog-title-input" type="text" value="<?php echo \htmlspecialchars($view_model->datum_item->description, ENT_QUOTES); ?>" name="blog_description" />
				
				<?php
					$blog_item_date = $view_model->datum_item->date;
					
					if (\strlen($blog_item_date) == 19) { 
						# ISO format
						$blog_item_date  = \DateTime::createFromFormat( 'Y-m-d H:i:s', $blog_item_date );
						
					} else if (\stripos($blog_item_date, '-') == 4) {
						# ISO short format
						$blog_item_date  = \DateTime::createFromFormat( 'Y-m-d', $blog_item_date );
						
					} else if (\stripos($blog_item_date, '-') == 2) {
						# short format
						$blog_item_date  = \DateTime::createFromFormat( 'm-d-Y', $blog_item_date );
					}
					
					$blog_item_date = $blog_item_date->format(  \championcore\wedge\config\get_json_configs()->json->date_format );
					
					$moment_format = \championcore\convert_date_format_php_to_moment( \str_replace( 'H:i:s', '', \championcore\wedge\config\get_json_configs()->json->date_format) );
				?>
				
				<label><?php echo $GLOBALS['lang_blog_date']; ?></label>
				<input class="blog-date-input" type="text" value="<?php echo \htmlspecialchars( $blog_item_date, ENT_QUOTES); ?>" name="head2" data-format="<?php echo $moment_format; ?>" />
				
				
				<label><?php echo $GLOBALS['lang_blog_tags']; ?></label>
				<input class="blog-tag-input" type="text" value="<?php echo \htmlspecialchars(\implode(', ', $view_model->datum_item->tags), \ENT_QUOTES); ?>" name="blog_tags" />
				
				<br />
				
				<label><?php echo $GLOBALS['lang_blog_url']; ?></label>
				<input class="blog-tag-input" type="text" value="<?php echo \htmlspecialchars((empty($view_model->datum_item->url) ? \str_replace(' ', '-', $view_model->datum_item->title) : $view_model->datum_item->url), ENT_QUOTES); ?>" name="blog_url" />
				
				<br />
				
				<div id="blog-featured-image" class="championcore-blog-featured-image" meta_featured_image="<?php echo \htmlspecialchars($view_model->datum_item->meta_featured_image); ?>">
					<label><?php echo $GLOBALS['lang_blog_featured_image']; ?></label>
					<input class="blog-tag-input" type="text" name="meta_featured_image" v-on:click="onclick_open" v-model="picked" ref="meta_featured_image" />
					<div class="add" v-on:click="onclick_open">
						<i class="fa fa-plus-square"></i>
					</div>
					<championcore-vue-modal v-bind:open="modal_open">
						<h3><?php echo $GLOBALS['lang_blog_featured_image']; ?></h3>
						<div class="image_list">
							<template v-for="item in image_list">
								<div v-if="item.champion_type == 'folder'" class="folder" v-on:click="onclick_select(item)">
									<img alt="image" v-bind:src="item.thumb" />
									<span v-html="item.champion_folder"></span>
								</div>
								<img v-if="item.champion_type != 'folder'" alt="image" v-bind:src="item.url" v-on:click="onclick_select(item)" />
							</template>
						</div>
					</championcore-vue-modal>
				</div>
				<br />
				
				<label>
					<input type="hidden"   value="no"  name="meta_indexed" />
					<input type="checkbox" value="yes" name="meta_indexed" <?php echo (($view_model->datum_item->meta_indexed == 'yes') ? 'checked' : ''); ?> />
					<?php echo $GLOBALS['lang_blog_index']; ?>
				</label>
				
				<label>
					<input type="hidden"   value="no"  name="meta_no_follow" />
					<input type="checkbox" value="yes" name="meta_no_follow" <?php echo (($view_model->datum_item->meta_no_follow == 'yes') ? 'checked' : ''); ?> />
					<?php echo $GLOBALS['lang_blog_nofollow']; ?>
				</label>
				
				<label><?php echo $GLOBALS['lang_blog_custom']; ?></label>
				<input class="blog-tag-input" type="text" value="<?php echo \htmlspecialchars($view_model->datum_item->meta_custom_description, \ENT_QUOTES); ?>" name="meta_custom_description" />
				
				<br />
			</div>
			
			<input type="hidden" name="filename" value="<?php echo $view_model->param_get_f . ".txt"; ?>" />
			<input type="hidden" name="fname"    value="<?php echo $view_model->fname[0]; ?>" />
			
			<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
			
			<!-- -->
			<div>
				<label><?php echo $GLOBALS['lang_blog_title']; ?></label>
				<input class="blog-title-input" type="text" value="<?php echo \htmlspecialchars( $view_model->datum_item->title, ENT_QUOTES); ?>" name="head1" />
			</div>
			<br />
			<!-- -->
			
			<?php
				$content = $view_model->datum_item->html;
				
				$editor  = (\championcore\wedge\config\get_json_configs()->json->wysiwyg == true) ? 'id="wysiwyg"' : 'id="textblock"';
				
				# handle forcing of textblock for editor
				$editor = (($view_model->force_textblock === true) ? 'id="textblock"' : $editor);
			?>
			
			<textarea spellcheck="false" <?php echo $editor;?> name="textblock"><?php echo htmlspecialchars($content); ?></textarea>
			
			<button class="btn save" type="submit" name="savetext"><?php echo $GLOBALS['lang_save']; ?></button>
			
			
			<?php if ((\championcore\wedge\config\get_json_configs()->json->integrate_rapidweaver === true) and (\stripos('champion', CHAMPION_ADMIN_URL) !== false)) { ?>
				<a class="btn preview-button" target="_blank" href="<?php echo \championcore\wedge\blog\storage\build_blog_url(\championcore\wedge\config\get_json_configs()->json->blog_url, $view_model->fname[1], $view_model->datum_item->title); ?>"><?php echo $GLOBALS['lang_home_preview']; ?></a>
			<?php } else { ?>
				<!-- <a class="btn preview-button" target="_blank" href="<?php echo \championcore\wedge\blog\storage\build_blog_url(\championcore\wedge\config\get_json_configs()->json->path . '/blog', $view_model->fname[1], $view_model->datum_item->title); ?>"><?php echo $GLOBALS['lang_home_preview']; ?></a> -->
				<a class="btn preview-button" target="_blank" href="<?php echo \championcore\wedge\blog\storage\build_blog_url(\championcore\wedge\config\get_json_configs()->json->path . '/' . $view_model->param_get_f, $view_model->file_info['filename'], $view_model->datum_item->title); ?>"><?php echo $GLOBALS['lang_home_preview']; ?></a>
			<?php } ?>
			
			
			<a href="#" class="btn toggle_duplicate_btn    btn toggle_embed_btn"><?php echo $GLOBALS['lang_create_embed']; ?></a>
			
			<a class="btn create-new" href="index.php?p=export-html-website&url=<?php echo \urlencode(CHAMPION_BASE_URL . \championcore\wedge\blog\storage\build_blog_url(\championcore\wedge\config\get_json_configs()->json->path . '/' . $view_model->param_get_f, $view_model->file_info['filename'], $view_model->datum_item->title)); ?>"><?php echo \htmlentities($GLOBALS['lang_export_html_button']); ?></a>

			<a target="_blank" class="media-manager" href="index.php?f=media"><?php echo $GLOBALS['lang_nav_img']; ?></a>
			
			<div class="float_barrier"></div>
			
		</form>
		<br />
		
		<div class="float_barrier"></div>
		<div class="toggle_meta_payload">
			<?php
				$embed_path = array_slice($view_model->fname,1);
				$embed_path = implode('/', $embed_path);
			?>
			
			<div class="tagdiv">
				<span><?php echo $GLOBALS['lang_create_embed_url']; ?></span>
				<input onclick="this.select()" type="text" class="embed_url" value="<?php echo "https://{$_SERVER['HTTP_HOST']}{$view_model->path}/end_point.php?item=",\urlencode($view_model->param_get_f); ?>" />
			</div>
			<?php /*
			<div class="tagdiv">
				<span>Embed Url (Relative):</span>
				<input onclick="this.select()" type="text" class="embed_url" value="{{end_point:<?php echo $_GET['f']; ?>}}" />
			</div>
			*/ ?>
			<div class="tagdiv">
				<span><?php echo $GLOBALS['lang_create_embed_html']; ?></span>
				<input onclick="this.select()" type="text" class="embed_url" value="<?php echo "<iframe id='iframe_embed_responsive' src='https://{$_SERVER['HTTP_HOST']}{$view_model->path}/end_point.php?item=",\urlencode($view_model->param_get_f), "' style='width: 100%; height: auto;'></iframe>"; ?>" />
			</div>
			
			<div class="tagdiv">
				<span><?php echo $GLOBALS['lang_create_embed_php']; ?></span>
				<input onclick="this.select()" type="text" class="embed_url" value="<?php echo "<?php readfile('https://{$_SERVER['HTTP_HOST']}{$view_model->path}/end_point.php?item=", \urlencode($view_model->param_get_f), "'); ?>"; ?>" />
			</div>
		</div>

		<?php 
			if (    \file_exists(CHAMPION_BASE_DIR . '/championcore/page/admin/openai/base.php')
			    and \file_exists(CHAMPION_BASE_DIR . '/championcore/page/admin/stable-diffusion/base.php')
			) { ?>
				<br />
				<script type="module">
					window.championcore.config = window.championcore.config || {};

					window.championcore.config.ai_image_generation = {
						base_url:           "<?php echo CHAMPION_BASE_URL; ?>",
						header:             "<?php echo \htmlentities($GLOBALS['lang_ai_image_header']); ?>",
						prompt:             "<?php echo \htmlentities($view_model->datum_item->ai_prompt); ?>",
						promptLabel:        "<?php echo \htmlentities($GLOBALS['lang_settings_ai_prompt']); ?>",
						source:             "<?php echo \htmlentities($view_model->datum_item->ai_source); ?>",
						sourceLabel:        "<?php echo \htmlentities($GLOBALS['lang_settings_ai_source']); ?>",
						open_settings_text: "<?php echo \htmlentities($GLOBALS['lang_settings_title']); ?>",

						translation_error: "<?php echo \htmlentities($GLOBALS['lang_ai_image_message_no_result']); ?>"
					};

					/**
					 * integrate widget
					 */
					const timer = window.setInterval(
						function () {

							if (window.championcore.global_message_bus) {

								// stop waiting
								window.clearInterval( timer );

								// attach
								window.championcore.global_message_bus.on(
									'ai-image-generation',
									function (evnt) {

										console.log( 'integration: ai-image-generation event', evnt );

										// show options
										const dom_hide = document.querySelector( 'form > .hide' );

										if ((dom_hide.style.display == '') || (dom_hide.style.display == 'none')) {
											jQuery('a.embed_toggle').trigger('click');
										}

										// scroll to blog featured image - delay so options toggle is expanded fully
										window.setTimeout(
											() => {
												document.querySelector( '#blog-featured-image' ).scrollIntoView();
												window.scrollBy( 0, -50 );
											},
											1000
										);
									}
								);
							}
						},
						1000
					);

				</script>
				<div id="ai-image-generation"></div>
	<?php } ?>

	<br />
	
	<?php
	}
	?>
</div>
