
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
	
	<a class="rename" href="<?php echo CHAMPION_ADMIN_URL; ?>/index.php?p=rename&d=<?php echo \htmlentities($view_model->param_get_f); ?>&e=<?php echo \htmlentities($view_model->param_get_ext); ?>">[<?php echo \htmlentities($GLOBALS['lang_rename_btn']); ?>]</a>
</div>

<div class="championcore">
	
	<br />
	
	<?php if (!$view_model->flag_has_content) {
		echo $GLOBALS['lang_no_content'];
	} else { ?>
		<?php if (in_array(strtolower('.' . $view_model->param_get_ext), $view_model->pics_files)) { ?>
			
			<?php #echo "<img class='img-preview animated zoomIn' src='{$view_model->path}/content/{$view_model->param_get_f}{$view_model->param_get_ext}' />", \PHP_EOL; ?>
			
			<div class="championcore-croppie" data-src="<?php echo "{$view_model->path}/content/{$view_model->param_get_f}.{$view_model->param_get_ext}?t={$view_model->now_now}"; ?>" style="max-width: 100%; width: <?php echo $view_model->dimen[0]; ?>px; height: <?php echo $view_model->dimen[1]; ?>px; "/></div>
			<a class="btn btn-crop"><?php echo $GLOBALS['lang_crop']; ?></a>
			<br />
			<br />
			<img class="crop-thumbnail" style="display: none;" alt="cropped" src="<?php echo  "{$view_model->path}/content/{$view_model->param_get_f}.{$view_model->param_get_ext}"; ?>" />
			<br />
			<br />
			
			<a class="btn" href="<?php echo CHAMPION_ADMIN_URL; ?>/index.php?p=media_upload_handler&gallery=<?php echo \dirname($view_model->param_get_f); ?>&item=<?php echo \basename($view_model->param_get_f), ".{$view_model->param_get_ext}"; ?>"><?php echo $GLOBALS['lang_media_replace']; ?></a>
			<br />
			<br />
			
			<form class="animated zoomIn" id="textfile" name="textfile" method="post" action="">
				<p>
					<label><?php echo $GLOBALS['lang_create_media_move']; ?></label>
					<select class="page-template-input" type='text' name='block_move'>
						<option value=""></option>
						<?php foreach ($view_model->media_piles as $value) { ?>
								<option value="<?php echo \htmlentities($value->get_location()); ?>" <?php echo (($view_model->media_pile_directory == $value->get_location()) ? 'selected' : ''); ?>><?php echo \htmlentities($value->get_location()); ?></option>
						<?php } ?>
					</select>
				</p>
				
				<button class="btn save" type="submit" name="savetext"><?php echo $GLOBALS['lang_save']; ?></button>
				
				<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
				
				<input type="hidden" name="filename"  value="<?php echo \str_replace(\championcore\get_configs()->dir_content, '', $view_model->filepath) . '.' . $view_model->param_get_ext; ?>" />
				<input type="hidden" name="fname"     value="<?php echo $view_model->fname[0]; ?>" />
				<input type="hidden" name="textblock" value="foo" />
			</form>
			<br />
			<br />
			<p class="img-info"><b><?php echo $GLOBALS['lang_gal_filename'];   ?></b><?php  echo $view_model->last_level, '.', $view_model->param_get_ext; ?></p>
			<p class="img-info"><b><?php echo $GLOBALS['lang_gal_dimensions']; ?></b>"<?php echo $view_model->dim; ?>"</p>
			<p class="img-info"><b><?php echo $GLOBALS['lang_gal_size'];       ?></b><?php  echo $view_model->size; ?> K</p>
			<p class="img-info"><b><?php echo $GLOBALS['lang_gal_img'];        ?></b>&#60;img src='<?php echo "{$view_model->path}/content/{$view_model->param_get_f}.{$view_model->param_get_ext}"; ?>' alt=''&#62;</p>
			<p class="img-info"><b><?php echo $GLOBALS['lang_gal_link'];       ?></b>&#60;a href='<?php echo "{$view_model->path}/content/{$view_model->param_get_f}.{$view_model->param_get_ext}"; ?>'&#62;Link Text&#60;/a&#62;</p>
			
			<?php
				$fname = $view_model->fname;
				
				include (CHAMPION_ADMIN_DIR . '/inc/captions.php');
			
		}
	}
	?>
</div>

