
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<div class="championcore">
	<!-- h1><?php echo \htmlentities($GLOBALS['lang_blog_import']); ?></h1 -->
	
	<?php if (isset($view_model->message) and \is_string($view_model->message) and (\strlen(\trim($view_model->message)) > 0) ) { ?>
		<p><?php echo \htmlentities($view_model->message); ?></p>
	<?php } ?>
	
	<form class="create-form" name="textfile" method="post" action="index.php?p=blog_import_from_rss&method=post" style="min-width: auto;">
		
		<input type="text" placeholder="<?php echo \htmlentities($GLOBALS['lang_blog_import_url']); ?>" value="" name="field[url]" required />
		
		<input type="text" placeholder="<?php echo \htmlentities($GLOBALS['lang_blog_import_page_var']); ?>" value="" name="field[page_var]" />
		
		<input type="text" placeholder="<?php echo \htmlentities($GLOBALS['lang_blog_import_page_max']); ?>" value="" name="field[page_max]" />
		
		<span class="comment"></span>
		
		<button class="btn" type="submit" name="import"><?php echo \htmlentities($GLOBALS['lang_blog_import']); ?></button>
		<a href="#" class="tooltip" alt="<?php echo \htmlentities($GLOBALS['lang_blog_import_tool_tip']); ?>">?</a>
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
	</form>
	
</div>
