
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<div class="championcore">
	<h1><?php echo $GLOBALS['lang_settings_customposttypes'];?></h1>
	<ul class="management">
		<?php foreach ($view_model->list as $key => $value) { ?>
			<li>
				<?php echo $this->escape($key); ?>
				<div class="op">
					<a href="index.php?p=custom_post_types&post_type_name=<?php echo $this->escape($key); ?>&method=get"><?php echo $GLOBALS['lang_settings_custompostmanage'];?></a>
				</div>
				<div class="op">
					<a href="index.php?p=custom_post_type_definitions&post_type_name=<?php echo $this->escape($key); ?>&method=put&csrf_token=<?php echo \championcore\session\csrf\create(); ?>"><?php echo $GLOBALS['lang_settings_custompostmanageedit'];?></a>
				</div>
				<div class="op">
					<a href="index.php?p=custom_post_type_definitions&post_type_name=<?php echo $this->escape($key); ?>&method=delete&csrf_token=<?php echo \championcore\session\csrf\create(); ?>">
						<img src="img/icon-delete.svg" />
					</a>
				</div>
				<div class="float_barrier"></div>
			</li>
		<?php } ?>
	</ul>
	
	<p>
		<a class="btn" href="index.php?p=custom_post_type_definitions&method=post&csrf_token=<?php echo \championcore\session\csrf\create(); ?>"><?php echo $GLOBALS['lang_settings_custompostmanageadd'];?></a> 
	</p>
	
</div>
