
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<div class="championcore">
	<div class='banner'><?php echo $GLOBALS['lang_delete']; ?> custom post type <span><?php echo $this->escape($view_model->post_type_name);?></span> ?</div>
	
	<p>
		<a href="index.php?p=custom_post_type_definitions&method=get"><?php echo $GLOBALS['lang_settings_custompostback'];?></a> 
	</p>
	
	<form class="delete-form" name="textfile" method="post" action="">	
		<a class="btn cancel" href="index.php?p=custom_post_type_definitions&method=get"><?php echo $GLOBALS['lang_cancel'];?></a>
		<button class="btn" type="submit" name="savetext"><?php echo $GLOBALS['lang_del_button'];?></button>
		
		<input type="hidden" name="field[tx][name]" value="tx"  />
		<input type="hidden" name="field[tx][type]" value="int" />
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
	</form>
</div>
