<style>
	.championcore form .form-row label {
    text-align: left;
    margin-bottom: 10px;
}
</style>

<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<div class="championcore">
	<h1><?php echo $GLOBALS['lang_settings_custompostdefadd'];?></h1>
	
	<p>
		<a href="index.php?p=custom_post_type_definitions&method=get"><?php echo $GLOBALS['lang_settings_custompostback'];?></a>
	</p>

	<form class="create-form" name="textfile" method="post" action="index.php?p=custom_post_type_definitions&method=post">
		
		<div class="form-row">
			<label for=""><?php echo $GLOBALS['lang_settings_custompostdeftypename'];?></label>
			<input type="text" placeholder="<?php echo $GLOBALS['lang_settings_custompostdeftypename'];?>" value="" name="post_type_name" />
			<span class="comment"></span>
		</div>
	
		<?php for ($k = 0; $k < 10; $k++) { ?>
			<h3><?php echo $GLOBALS['lang_settings_custompostdeffield'];?>: <?php echo $this->escape($k + 1); ?></h3>	
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdefname'];?></label>
				<input type="text" placeholder="<?php echo $GLOBALS['lang_settings_custompostdefname'];?>" value="" name="field[<?php echo $this->escape($k); ?>][name]" />
				<span class="comment"></span>
			</div>
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdeftype'];?></label>
				<select name="field[<?php echo $this->escape($k); ?>][type]">
					<option value="audio">audio</option>
					<option value="image">image</option>
					<option value="text" selected>text</option>
					<option value="textarea">textarea</option>
					<option value="video">video</option>
				</select>
			</div>
		<?php } ?>
		
		<br />
		<br />
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
		
		<button class="btn" type="submit" name="save_configs"><?php echo $GLOBALS['lang_save'];?></button>
	</form>
</div>

