<style>
	.championcore form .form-row textarea {
	    padding: 6px 8px 6px 8px;
	}
	.championcore form .form-row label {
	text-align: left;
	margin-bottom: 10px!important;
}
</style>

<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<div class="championcore">
	<h1><?php echo $GLOBALS['lang_settings_title_custompostedit_titlein'];?></h1>
	
	<p>
		<a href="index.php?p=custom_post_type_definitions&method=get"><?php echo $GLOBALS['lang_settings_custompostback'];?></a> 
	</p>
	
	<form class="create-form" name="textfile" method="post" action="index.php?p=custom_post_type_definitions&post_type_name=<?php echo $this->escape($view_model->datum->post_type_name);?>&method=put">
		
		<?php $ppp = 0;
			foreach ((array)($view_model->datum->fields) as $value) {
		?>
			<h3>Field: <?php echo $this->escape($value->name); ?></h3>	
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdefname'];?></label>
				<input type="text" placeholder="<?php echo $GLOBALS['lang_settings_custompostdefname'];?>" value="<?php echo $this->escape($value->name); ?>" name="field[<?php echo $this->escape($ppp); ?>][name]" />
				<span class="comment"></span>
			</div>
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdeftype'];?></label>
				<select name="field[<?php echo $this->escape($ppp); ?>][type]">
					<option value="audio"    <?php echo (($value->type == 'audio'   ) ? 'selected' : ''); ?>>audio</option>
					<option value="image"    <?php echo (($value->type == 'image'   ) ? 'selected' : ''); ?>>image</option>
					<option value="text"     <?php echo (($value->type == 'text'    ) ? 'selected' : ''); ?>>text</option>
					<option value="textarea" <?php echo (($value->type == 'textarea') ? 'selected' : ''); ?>>textarea</option>
					<option value="video"    <?php echo (($value->type == 'video'   ) ? 'selected' : ''); ?>>video</option>
				</select>
			</div>
		<?php 
				$ppp++;
			}
		?>
	
	
		<?php for ($k = $ppp; $k < 10; $k++) { ?>
			<h3><?php echo $GLOBALS['lang_settings_custompostdeffield'];?>: <?php echo $this->escape($k + 1); ?></h3>	
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdefname'];?></label>
				<input type="text" placeholder="<?php echo $GLOBALS['lang_settings_custompostdefname'];?>" value="" name="field[<?php echo $this->escape($k); ?>][name]" />
				<span class="comment"></span>
			</div>
			<div class="form-row">
				<label for=""><?php echo $GLOBALS['lang_settings_custompostdeftype'];?></label>
				<select name="field[<?php echo $this->escape($k); ?>][type]">
					<option value="audio">audio</option>
					<option value="image">image</option>
					<option value="text" selected>text</option>
					<option value="textarea">textarea</option>
					<option value="video">video</option>
				</select>
			</div>
		<?php } ?>
		
		<br />
		<br />
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
		
		<button class="btn" type="submit" name="save_configs"><?php echo $GLOBALS['lang_save'];?></button>
	</form>
	
</div>
