
<!-- bread crumbs -->
<div class="breadcrumb">
	<?php include (CHAMPION_ADMIN_DIR . '/inc/breadcrumbs.php'); ?>
</div>

<?php
# pagination helper
	$view_helper_pagination = new \championcore\view\helper\Pagination(); 
	echo $view_helper_pagination->render(
		[
			'max_pages' => $view_model->total_pages,
			'base_url'  => ('?f=pages'),
			
			'page'       => ((int)$view_model->cur_page),
			
			'css_class'      => 'older',
			'next_css_class' => 'older',
			'prev_css_class' => 'older'
		]
	);
?>

<div class="championcore import-html-page">
	<h1><?php echo \htmlentities($GLOBALS['lang_import_html_page_header']); ?> </h1>

	<form class="create-form" name="textfile" method="post" action="index.php?p=import-html-page&method=post" style="min-width: auto;">
		
		<div>
			<label><?php echo \htmlentities($GLOBALS['lang_import_html_page_url']); ?></label>
			<input type="text" placeholder="<?php echo \htmlentities($GLOBALS['lang_import_html_page_url']); ?>" value="" name="field[url]" />
		</div>

		<div>
			<label><?php echo \htmlentities($GLOBALS['lang_import_html_page_text']); ?></label>
			<textarea name="field[text]" spellcheck="false"></textarea>
		</div>
		
		<button class="btn" type="submit" name="import"><?php echo \htmlentities($GLOBALS['lang_blog_import']); ?></button>
		
		<input type="hidden" name="csrf_token" value="<?php echo \championcore\session\csrf\create(); ?>" />
	</form>
	
	<div class="championcore_float_barrier"></div>
</div>

<a class='btn create-new' href='index.php?p=create'><?php echo \htmlentities($GLOBALS['lang_home_new']); ?></a>
<a class='btn create-new' href='index.php?p=export-html-website'><?php echo \htmlentities($GLOBALS['lang_export_html_button']); ?></a>
<a class='btn create-new' href='index.php?p=import-html-page'><?php echo \htmlentities($GLOBALS['lang_import_html_button']); ?></a>

<?php
	if ($view_model->cur_page < $view_model->total_pages) { 
		echo "<a class='older' href='index.php?f=pages&pnum=".($view_model->cur_page+1)."'>></a>"; 
	}
	if ($view_model->cur_page > 1) { 
		echo "<a class='newer' href='index.php?f=pages&pnum=".($view_model->cur_page-1)."'><</a>"; 
	}
?>