
<div class='breadcrumb'>
	<a href="<?php echo CHAMPION_ADMIN_URL; ?>"><?php echo $GLOBALS['lang_nav_home']; ?></a> / <?php echo $GLOBALS['lang_nav_stats']; ?>
	<a href="#" class='rename' onClick="window.location.href=window.location.href"><?php echo $GLOBALS['lang_stats_refresh']; ?></a>
</div>

<div id="content">
	
	<!-- weekly visitors -->
	<div class="stats-group first-one">
		<p class="stat-title"><?php echo $GLOBALS['lang_stats_thisweek']; ?></p>
		
		<?php if (empty($view_model->stats->weekly->visitors)) { ?>
			<p style="color:#aaa"><?php echo $GLOBALS['lang_stats_nodata']; ?></p> 
			
		<?php } else {
			
			# bar chart
			$weekly_visitor_sum   = \array_sum($view_model->stats->weekly->visitors);
			# $weekly_visitor_ratio = max($view_model->stats->weekly->visitors);
			# $weekly_visitor_ratio = ($weekly_visitor_ratio == 0) ? 0 : (floatval($weekly_visitor_sum)/floatval($weekly_visitor_ratio));
			
			foreach ($view_model->stats->weekly->visitors as $day => $visitors) {
				
				$ddd = \DateTime::createFromFormat('Y-m-d', $day );
				$ddd = $ddd->format( 'M d' );
				
				# $bar_height = $weekly_visitor_ratio * $visitors;
				
				$percentage = 100.0 * ((float)$visitors)/((float)$weekly_visitor_sum);
				$bar_height = $percentage;
?>
			<div class="bar-container">
				<div title = "<?php echo $visitors, '/', $weekly_visitor_sum, ', ', \sprintf('%2d',$bar_height), '% - ', $ddd; ?>" rel = "tooltip" class = "bar-fill <?php if ($ddd == date('M d')){ echo 'blue-bar'; } ?>" style = "height:<?php echo $bar_height; ?>%;">
				</div>
			</div>
	<?php
			}
		}
	?>
	</div>
	
	<!-- daily -->
	<div class="stats-group group">
		<p class="stat-title"><?php echo  \htmlentities($GLOBALS['lang_stats_todays_stats']); ?></p>
		
		<!-- Number of visitors -->
		<div class="black">
			<p class="num"><?php echo  \htmlentities($view_model->stats->daily->visitors); ?></p>
			<p class="desc"><?php echo \htmlentities($GLOBALS['lang_stats_today']); ?></p>
		</div>
		
		<!-- Number of page views -->
		<div class="black">
			<p class="num"><?php echo  \htmlentities($view_model->stats->daily->page_views); ?></p>
			<p class="desc"><?php echo \htmlentities($GLOBALS['lang_stats_pageviews']); ?></p>
		</div>
		
		<!-- Number of page views per visit -->
		<div class="black">
			<p class="num"><?php echo  \htmlentities( ( ($view_model->stats->daily->visitors > 0) ? round(floatval($view_model->stats->daily->page_views)/floatval($view_model->stats->daily->visitors)): 0) ); ?></p>
			<p class="desc"><?php echo \htmlentities($GLOBALS['lang_stats_per_visit']); ?></p>
		</div>
		
		<!-- Number Bounce rate -->
		<div class="black">
			<p class="num"><?php echo  \htmlentities($view_model->stats->daily->bounce_rate); ?></p>
			<p class="desc"><?php echo \htmlentities($GLOBALS['lang_stats_bounce_rate']); ?></p>
		</div>
	</div>
	
	
	
	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_pages']); ?></p>
		
		<?php if (!empty($view_model->stats->pages)) {
			##################
			# Top 10 pages 
			$nb_pages = 10;
			
			foreach ($view_model->stats->pages as $key => $value ) {
				
				if ($key == '') {
					continue;
				}
				
				if ($nb_pages > 0) {
					$nb_pages--;
				} else {
					break;
				}
				
				echo \htmlentities($value); ?><a target="_blank" class="stats-link" href="<?php echo \urlencode($key); ?>"><?php echo \htmlentities(\substr($key, 0,60)); ?></a><br>
				<?php
			}
		}
	?>
	</div>
	
	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_refers']); ?></p>
		
		<?php if (!empty($view_model->stats->referrers)) {
			##################
			# Top 10 referers
			$nb_referrers = 10;
			
			foreach ($view_model->stats->referrers as $key => $value) {
				
				if ($key == '') {
					continue;
				}
				
				if ($nb_referrers > 0) {
					$nb_referrers--;
				} else {
					break;
				}
				
				echo \htmlspecialchars($value, \ENT_QUOTES, 'UTF-8'), " &nbsp; ", "<a target=\"_blank\" class=\"stats-link\" href='//",$key,"'>", substr(htmlspecialchars($key, \ENT_QUOTES, 'UTF-8'), 0,60), "</a><br>\n";
			}
		}
	?>
	</div>
	
	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_browsers']); ?></p>
		
		<?php if (!empty($view_model->stats->browsers)) {
			##################
			# top 10 browsers
			
			$nb_browsers = 10;
			
			$sum_count        = \array_sum( $view_model->stats->browsers );
			$sum_count_so_far = 0;
			
			foreach ($view_model->stats->browsers as $key => $value) {
				
				if ($key == '') {
					continue;
				}
				
				if ($nb_browsers > 0) {
					$nb_browsers--;
				} else {
					break;
				}
				
				$sum_count_so_far += \intval($value);
				
				echo \htmlspecialchars($key, \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($value)/\floatval($sum_count)), "<br \>\n";
			}
			
			echo \htmlspecialchars('Other', \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($sum_count - $sum_count_so_far)/\floatval($sum_count)), "<br \>\n";
		}
	?>
	</div>
	
	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_countries']); ?></p>
		
		<?php if (!empty($view_model->stats->countries)) {
			##################
			# top 10 countries
			
			$nb_countries = 10;
			
			$sum_count        = \array_sum( $view_model->stats->countries );
			$sum_count_so_far = 0;
			
			foreach ($view_model->stats->countries as $key => $value) {
				
				if ($key == '') {
					continue;
				}
				
				if ($nb_countries > 0) {
					$nb_countries--;
				} else {
					break;
				}
				
				$sum_count_so_far += \intval($value);
				
				echo \htmlspecialchars($key, \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($value)/\floatval($sum_count)), "<br \>\n";
			}
			echo \htmlspecialchars('Other', \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($sum_count - $sum_count_so_far)/\floatval($sum_count)), "<br \>\n";
		}
	?>
	</div>

	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_devices']); ?></p>
		
		<?php if (!empty($view_model->stats->devices)) {
		#############
		# top 10 devices
		
		$nb_devices = 10;
		
		$sum_count        = \array_sum( $view_model->stats->devices );
		$sum_count_so_far = 0;
		
		foreach ($view_model->stats->devices as $key => $value) {
			
			if ($key == '') {
				continue;
			}
			
			if ($nb_devices > 0) {
				$nb_devices--;
			} else {
				break;
			}
			
			$sum_count_so_far += \intval($value);
			
			echo \htmlspecialchars($key, \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($value)/\floatval($sum_count)), "<br \>\n";
		}
		
		echo \htmlspecialchars('Other', \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($sum_count - $sum_count_so_far)/\floatval($sum_count)), "<br \>\n";
		} 
	?>
	</div>
	
	<!-- -->
	<div class="stats-group stats-list">
		<p class="stat-title"><?php echo \htmlentities($GLOBALS['lang_stats_systems']); ?></p>
		
		<?php if (!empty($view_model->stats->systems)) {
			#############
			# top 10 systems
			
			$nb_systems = 10;
			
			$sum_count        = \array_sum( $view_model->stats->systems );
			$sum_count_so_far = 0;
			
			foreach ($view_model->stats->systems as $key => $value) {
				
				if ($key == '') {
					continue;
				}
				
				if ($nb_systems > 0) {
					$nb_systems--;
				} else {
					break;
				}
				
				$sum_count_so_far += \intval($value);
				
				echo \htmlspecialchars($key, \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($value)/\floatval($sum_count)), "<br \>\n";
			}
			
			echo \htmlspecialchars('Other', \ENT_QUOTES, 'UTF-8'), " &nbsp; ", \sprintf('%2d%%', 100.0*\floatval($sum_count - $sum_count_so_far)/\floatval($sum_count)), "<br \>\n";
		}
	?>
	</div>
	
</div>

