
<div class="championcore tag flexslider">
	
	<ul class="slides">
		<?php foreach ($view_model->images->lines as $iii) { ?>
			<li>
				<a title="<?php echo \htmlentities($iii->caption); ?>" href="<?php echo $view_model->url_path; ?><?php echo $iii->url; ?>">
					<img class="imagelightbox"
						 alt="<?php echo \htmlentities($iii->alt); ?>"
						 title="<?php echo \htmlentities($iii->caption); ?>"
						 src="<?php echo $view_model->url_path; ?><?php echo $iii->url_thumbnail; ?>" />
				</a>
			</li>
		<?php } ?>
	</ul>
	
	<?php foreach ($view_model->hidden_images_for_popup as $iii) { ?>
		<?php if (!\in_array($iii, $view_model->images->lines)) { ?>
			<a title="<?php echo \htmlentities($iii->caption); ?>"
			   href="<?php echo $view_model->url_path; ?><?php echo $iii->url; ?>" style="display: none; visibility: hidden;">
				<img
					class="imagelightbox"
					alt="<?php echo \htmlentities($iii->alt); ?>"
					src="<?php echo $view_model->url_path; ?><?php echo $iii->url_thumbnail; ?>"
					style="height: <?php echo isset(\championcore\wedge\config\get_json_configs()->json->thumbnail_height) ? \championcore\wedge\config\get_json_configs()->json->thumbnail_height . 'px': 'auto'; ?>"
				/>
			</a>
		<?php } ?>
	<?php } ?>
	
</div>
