
<!-- Facebook -->
<?php foreach ($view_model->facebook->admins as $value) { ?>
	<meta property="fb:admins" content="<?php echo $this->escape( \trim($value) ); ?>" />
<?php } ?>
<meta property="fb:app_id" content="<?php echo $this->escape(\championcore\wedge\config\get_json_configs()->json->ogp_facebook_id); ?>" />

<!-- Open Graph meta data -->
<meta property="og:title"       content="<?php echo $this->escape($view_model->page_title); ?>" />
<meta property="og:type"        content="<?php echo $this->escape($view_model->ogp->ogtype); ?>" />
<meta property="og:url"         content="<?php echo $this->escape($view_model->url); ?>" />
<meta property="og:description" content="<?php echo $this->escape($view_model->page_description); ?>" />
<meta property="og:site_name"   content="Champion CMS <?php echo \htmlentities($GLOBALS['champion_version']); ?>" />

<?php if ($view_model->image_url !== false) { ?>
	<meta property="og:image"    content="<?php echo $this->escape($view_model->image_url); ?>" />
	<meta name="og:image:width"  content="<?php echo $this->escape($view_model->image_width); ?>" />
	<meta name="og:image:height" content="<?php echo $this->escape($view_model->image_height); ?>" />
<?php } ?>

<!-- Schema.org meta data -->
<meta itemprop="name"    content="<?php echo $this->escape($view_model->page_title); ?>" />
<meta name="description" content="<?php echo $this->escape($view_model->page_description); ?>" />

<?php if ($view_model->image_url !== false) { ?>
	<meta property="image"       content="<?php echo $this->escape($view_model->image_url); ?>" />
	<meta name="og:image:width"  content="<?php echo $this->escape($view_model->image_width); ?>" />
	<meta name="og:image:height" content="<?php echo $this->escape($view_model->image_height); ?>" />
<?php } ?>

<link rel="canonical" href="<?php echo \htmlentities($view_model->schema_org->canonical); ?>" />
<meta property="article:published_time" content="<?php echo $this->escape($view_model->created_on ->format('d/m/Y H:i:s')); ?>" />
<meta property="article:modified_time"  content="<?php echo $this->escape($view_model->modified_on->format('d/m/Y H:i:s')); ?>" />

<!-- Twitter card meta data -->
<meta name="twitter:url"         content="<?php echo $this->escape($view_model->url); ?>" />
<meta name="twitter:card"        content="summary" />
<meta name="twitter:creator"     content="<?php echo $this->escape(\championcore\wedge\config\get_json_configs()->json->ogp_twitter_creator); ?>" />
<meta name="twitter:site"        content="<?php echo $this->escape(\championcore\wedge\config\get_json_configs()->json->ogp_twitter_username); ?>" />
<meta name="twitter:title"       content="<?php echo $this->escape($view_model->page_title); ?>" />
<meta name="twitter:description" content="<?php echo $this->escape($view_model->page_description); ?>" />

<?php if ($view_model->image_url !== false) { ?>
	<meta name="twitter:image"       content="<?php echo $this->escape($view_model->image_url); ?>" />
<?php } ?>
